# Generated by Django 2.2 on 2020-12-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201207_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default=1234567890, max_length=50),
            preserve_default=False,
        ),
    ]
