# Generated by Django 2.2 on 2020-12-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_reservations', '0002_auto_20201207_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspot',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='spot_type',
            field=models.IntegerField(
                choices=[(2, 'Two-wheeler'), (4, 'Four-wheeler')], default=4
            ),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='status',
            field=models.CharField(
                choices=[('A', 'A'), ('R', 'R'), ('S', 'S')], default='A', max_length=1
            ),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
